### ISSUE TITLE
Invalid viewstate. 
	Client IP: 98.159.78.117
	Port: 12352
	Referer: https://www.arkansasrepeatercouncil.org/repeaters/?q=&p=7
	Path: /repeaters/default.aspx
	User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1
	ViewState: /wEPDwUJMjMxNzQ0NDEwZGSkaUDsXY0bDgCT20Ty8DBmchoaN3PUwLKXyznlEwikaA==

### ISSUE THREAD

**Issue by hiram-maxim** [ArkansasRepeaterCouncil/website#308]
### Message
> Validation of viewstate MAC failed. If this application is hosted by a Web Farm or cluster, ensure that <machineKey> configuration specifies the same validationKey and validation algorithm. AutoGenerate cannot be used in a cluster.
> 
> See http://go.microsoft.com/fwlink/?LinkID=314055 for more information.

### Help link
> 

### Source
> System.Web

### Stack trace
>    at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
>    at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
>    at System.Web.UI.ObjectStateFormatter.System.Web.UI.IStateFormatter2.Deserialize(String serializedState, Purpose purpose)
>    at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
>    at System.Web.UI.HiddenFieldPageStatePersister.Load()
>    at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
>    at System.Web.UI.Page.LoadAllState()
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>    at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>    at System.Web.UI.Page.ProcessRequest()
>    at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
>    at System.Web.UI.Page.ProcessRequest(HttpContext context)
>    at ASP.repeaters_default_aspx.ProcessRequest(HttpContext context) in d:\Temp\Temporary ASP.NET Files\root\154c7ec3\82e72b46\App_Web_s2etyg5i.0.cs:line 0
>    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by JoshuaCarroll** [comment]
There is too little information provided to track down the cause of this issue.
