### ISSUE TITLE
information updating

### ISSUE THREAD

**Issue by w5rhs** [ArkansasRepeaterCouncil/website#313]
**Description of the bug** When updating a new repeater Information says it was saved but when you go back to the repeater listing it doesn't say that it was updated. Plus when you try to update the status to operational it asks for all the repeater information again instead of copying over what you put in for coordination request.

**Steps to reproduce the behavior**

**Clear description of what you expected to happen**

**Additional information**

**Comment by JoshuaCarroll** [comment]
I believe this is fixed now.  Can you please try again and confirm?

**Comment by JoshuaCarroll** [comment]
I believe this issue is fixed.
