### ISSUE TITLE
Need a way for coordinators to override business rules

### ISSUE THREAD

**Issue by JoshuaCarroll** [ArkansasRepeaterCouncil/website#613]
**Is your feature request related to a problem? Please describe.**
Business rules outlined in the procedures are currently enforced in the UI.  Need a way for coordinators to override them for exceptions. 

**Describe the solution you'd like**
If the change is in violation of a business rule, and if the current user is a coordinator, display a checkbox that allows them to override the business rule logic.

**Describe alternatives you've considered**
Exceptions could be entered in the database directly, but that's stupid.  Don't be stupid.

**Additional information**

**Comment by temmoore** [comment]
This will be very helpfull
