### ISSUE TITLE
Multiple Input PL Tones

### ISSUE THREAD

**Issue by k5dvt** [ArkansasRepeaterCouncil/website#615]
**Is your feature request related to a problem? Please describe.**
          Not really related to a problem, but a suggestion.

**Describe the solution you'd like**
       A small tick box to the side of the Receiver PL Tone. When checked, it enables for multiple input PL tones to be entered and added to the repeater's info. Perhaps (Since my situation is remote "Satellite" Receivers) a text box location (Such as "Kessler Mountain, South East Fayetteville Input") of that receiver _could_ be added as well.

**Describe alternatives you've considered**
       Just putting the tones with locations in the notes section.

**Additional information**
       None. :) Thanks for all the hard work!!!

**Comment by JoshuaCarroll** [comment]
This another good idea.  Right now the notes are only available to coordinators and the respective trustee and users of the repeater.  So I guess the question would be, what would be more useful: a public "additional information" field or an option for multiple PL tones, or both?  

Let's discuss the merits here.

**Comment by Jonthetrombonist** [comment]
An "Additional information" field sounds like a good idea actually. It will
give the listing a little bit of "elbow room" for customized features as
well (not just the PL tone case).

However I do like the option still for multiple PLs. The council for years
has recorded other operational data, like if the repeater was on battery
back up, held a weather net, etc... Info that doesn't necessarily effect
the operational parameters for coordination, but still convenient details
to know none the less.

**Comment by JoshuaCarroll** [comment]
Created "additional information" field for this, and any other, information.
