### ISSUE TITLE
Link system search

### ISSUE THREAD

**Issue by k5dvt** [ArkansasRepeaterCouncil/website#616]
**Is your feature request related to a problem? Please describe.**
                       No.

**Describe the solution you'd like**
                    A Tick box when checked enables a text box or drop down box that allows for the repeater to be listed as a member of a large linked system. This is to aide in the search in the directory for repeaters as part of a link system that carries more than one call sign or the call sign of the linked system. For Example:
There is a Link system called the NWA Link system and carries the call N5UFO. If you search N5UFO you will see all repeaters carrying that call, some of which are and some which are not on the linked system. You also miss the W5KMP, KG5OQF and K5DVT Repeaters that are linked as well.

**Describe alternatives you've considered**
          Adding "A Member of the NWA Link system" in the notes box, but I am uncertain if that is search through during a new search query, 

**Additional information**

**Comment by JoshuaCarroll** [comment]
This is an interesting idea, and I can definitely see the value in it.

<design notes>
My initial thought was to create a parent/child relationship between repeaters.  That's fine but that might be confusing for some people, as their system architecture may not resemble that relationship.

My second thought is that a "Link system" could be created as a new entity.  I'd need to create an interface for creating and maintaining "Link systems".  That could drop into a table with `link system id`, `link system name`, `link system owner id` (fk to users.id), and another table with `link id`, `link system id`, `repeater id` (fk to repeaters.id)

In the UI implementation, if a repeater is part of a link system, that could be displayed on a separate tab on the repeater details page.  Each listing would have a link to that repeater's detail page.

**Comment by Jonthetrombonist** [comment]
I was thinking the parent/child relationship too. Most systems as you know
have a hub repeater, but it isn't always the case.

In repeaterbook they won't allow someone to list a repeater "System" unless
it has >= 3 repeaters. Other than that it just lists the repeaters as
linked, and not as a system. Maybe that's some food for thought?

**Comment by JoshuaCarroll** [comment]
1. Create a table `Links`.  This should contain internal `LinkID` (int), `LinkFrom` (int), and `LinkTo` (int).
2. Add `Links` to repeater update page. (New tab?)
3. Add support for links to the GetRepeaterDetails stored procedure.
4. Consume new links information on repeater update page
5. Add support for links to the GetRepeaterDetailsPublic stored procedure.
6. Consume new links information on public repeater details page

**Comment by JoshuaCarroll** [comment]
1. ~~Create a table Links. This should contain internal LinkID (int), LinkFrom (int), and LinkTo (int).~~
2. Add Links to repeater update page. (New tab?)
3. Add support for links to the GetRepeaterDetails stored procedure.
4. Consume new links information on repeater update page
5. Add support for links to the GetRepeaterDetailsPublic stored procedure.
6. Consume new links information on public repeater details page
