### ISSUE TITLE
Make repeater database downloadable to a spreadsheet platform

### ISSUE THREAD

**Issue by WX0X** [ArkansasRepeaterCouncil/website#622]
**Is your feature request related to a problem? Please describe.**
Not a problem, an enhancement to make the database user friendly and downloadable to any programming software. 

**Describe the solution you'd like**
Make the repeater database and all public information able to be output to a Microsoft excel file. 

**Describe alternatives you've considered**

**Additional information**
Under the old website it was a simple select/copy/paste to get all information into an Excel file that was easily editable/sortable that would allow input to any programming software. This information included county/municipality information along with other information collected by the council.

**Comment by JoshuaCarroll** [comment]
What would be the purpose of using the information in this format?  I'd rather create something that would serve the end-state goal than just an intermediate step.

**Comment by JoshuaCarroll** [comment]
Merging into #625
