### ISSUE TITLE
Request form fails on decimal entry for antenna height

### ISSUE THREAD

**Issue by brooksevans** [ArkansasRepeaterCouncil/website#627]
I didn't take the time to look beyond the submit, but workflow fails (without error) when someone submits an antenna height with a decimal. I submitted "45.4". The form submits but the request seems to be dumped.

**Comment by JoshuaCarroll** [comment]
Fixed.  Please try again.

Changed the datatype for the AntennaHeight parameter from int to decimal(10,2) in the stored procedure
