### ISSUE TITLE
Repeater corrdination not working

### ISSUE THREAD

**Issue by k5cwr** [ArkansasRepeaterCouncil/website#629]
I filed about 6 or 7 months ago for the coordination of a UHF repeater 444.800/449.800 I never got any reply back. I have the repeater up and running with no interference. This is a d-star repeater.

I have screen shots from attempting to refile this coordination.
![image](https://user-images.githubusercontent.com/59593093/71869173-ac4bba00-30d6-11ea-9efd-e690f27fb6fe.png)

This is the screen I get after hitting the submit button
![image](https://user-images.githubusercontent.com/59593093/71869195-c5ed0180-30d6-11ea-82e1-938c0674fd4c.png)

I have also submitted this to repeater book so it is listed there.

**Comment by JoshuaCarroll** [comment]
Need to change the datatype of AntennaHeight from int to Double(6,2)

**Comment by JoshuaCarroll** [comment]
Fixed.  Please try again.

**Comment by k5cwr** [comment]
Just re-submitted.

 

Thanks,

 

cid:f920dcad60a066b046a458272d2d6b26e4345ea9f6838f372433e49bde2d3a16f8b8f3023b.mpf

  

Carl Richardson 

Driven Elements Amateur Radio Group 

ARS: K5CWR 

146 Lawrence RD 2645 

Smithville, AR 

870-528-7227
