### ISSUE TITLE
Callsign Hyperlink

### ISSUE THREAD

**Issue by k5dvt** [ArkansasRepeaterCouncil/website#638]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a hyperlink on the Repeater Owner and Trustee that takes you to their respective QRZ pages.

**Describe alternatives you've considered**
None.

**Additional information**
Perhaps instead of QRZ, another use could be for looking up those calls inside the database it's self.

**Comment by JoshuaCarroll** [comment]
Great idea.  We already have this on our reports and admin pages.. not sure why I didn't think to add this already.  Thanks!

**Comment by JoshuaCarroll** [comment]
Done
