### ISSUE TITLE
Rendering issues on Google Chrome on Android Device

### ISSUE THREAD

**Issue by frankster2000** [ArkansasRepeaterCouncil/website#643]
Pretty much any link I clicked on including the Home link would not render the page correct.   When I tried to sign up for a new account, it popped up the "something went wrong" page.  Home link did the same thing when trying to navigate around from the top menu.

**Comment by JoshuaCarroll** [comment]
(I really should look at these more often, but alas, you sent this during football season which is a very busy time of year for me.)

Can you please verify this is still a problem?  If so, can you add a screenshot or two to this issue?

**Comment by frankster2000** [comment]
Links appear to be working and rendering now on my phone.   Not sure if something changed on your end, or it was an update to chrome, but it's working now.
