### ISSUE TITLE
Historical Look up - "Did you mean _____?" search optimization 

### ISSUE THREAD

**Issue by k5dvt** [ArkansasRepeaterCouncil/website#653]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think this is better explained with an example:

Look up "W5NWA" and have it return something like "Did you mean N5NBJ's 444.8 and 442.9 machines?"
They used to have the call of W5NWA, but now they have the call of N5NBJ.

The whole thinking behind this is that some folks may refer to a repeater as the "W5ABC" repeater, when in fact it may have just changed hands or been re-coordinated. Some hams keep their repeater list on old dead tree carcass, and may not have realized that the repeater changed callsigns when they go to look up info on it.

**Comment by JoshuaCarroll** [comment]
I think this is a good idea, but we currently don't maintain historical data on repeaters.  So this wouldn't be possible.
