### ISSUE TITLE
Table overflow

### ISSUE THREAD

**Issue by k5dvt** [ArkansasRepeaterCouncil/website#656]
"Repeater Most Wanted" table overflowed on front landing page. Picture:
![image](https://user-images.githubusercontent.com/25829119/193147584-a1c45477-55d4-4959-9c64-d8039510af8a.png)

I'm running Chrome 105.0.5195.128 64-Bit on Windows 11 with a screen resolution of 1366x768. Seems like it was supposed to all be contained in the class "homepageListing mostWanted".

**Comment by alexpalade** [comment]
Same here, both columns overflow. Tested in Firefox and Chrome on Linux, with a 1366x768 resolution.
I think it's because the container div has a fixed height of 850px from the [homepageListing class](https://github.com/ArkansasRepeaterCouncil/website/blob/d8babf21d094c499aa2208302b82b73943ed3e8f/css/arc.css#L229).
[](url)

**Comment by ae5au** [comment]
@k5dvt this specific problem is fixed, but there are still some CSS issues to work out. Specifically, the most wanted table won't go as narrow as the box around it...

well, nevermind removing the height works great in Firefox but caused other issues in Chrome. Reopening

**Comment by ae5au** [comment]
Ok, back again. The problem wasn't a difference between FF and Chrome...it was there on both. The table for expired most wanted was overflowing to the right if the width was too narrow. Quick and dirty fix for that now by setting min-width to min-content for the div. Has the side effect of flowing to a stack that only uses half of the width, but at least nothing is busting out at this point.

Going to close this issue and make an enhancement issue to make this more responsive.

Merged #659
