### ISSUE TITLE
Exception is thrown when you attempt to create a new account

### ISSUE THREAD

**Issue by JoshuaCarroll** [ArkansasRepeaterCouncil/website#661]
Exception is thrown when you attempt to create a new account.

> Server Error in '/' Application.
> The request was aborted: Could not create SSL/TLS secure channel.
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
> 
> Exception Details: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
> 
> Source Error:
> 
> The source code that generated this unhandled exception can only be shown when compiled in debug mode. To enable this, please follow one of the below steps, then request the URL:
> 
> 1. Add a "Debug=true" directive at the top of the file that generated the error. Example:
> 
>   <%@ Page Language="C#" Debug="true" %>
> 
> or:
> 
> 2) Add the following section to the configuration file of your application:
> 
> <configuration>
>    <system.web>
>        <compilation debug="true"/>
>    </system.web>
> </configuration>
> 
> Note that this second technique will cause all files within a given application to be compiled in debug mode. The first technique will cause only that particular file to be compiled in debug mode.
> 
> Important: Running applications in debug mode does incur a memory/performance overhead. You should make sure that an application has debugging disabled before deploying into production scenario.
> 
> Stack Trace:
> 
> 
> [WebException: The request was aborted: Could not create SSL/TLS secure channel.]
>    System.Net.HttpWebRequest.GetResponse() +1463
>    Utilities.GetResponseFromUrl(String url) +165
>    LoginRequest.CustomValidator1_ServerValidate(Object source, ServerValidateEventArgs args) +145
>    System.Web.UI.WebControls.CustomValidator.OnServerValidate(String value) +149
>    System.Web.UI.WebControls.CustomValidator.EvaluateIsValid() +96
>    System.Web.UI.WebControls.BaseValidator.Validate() +92
>    System.Web.UI.Page.Validate() +172
>    System.Web.UI.Page.Validate(String validationGroup) +9864143
>    System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +179
>    System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12
>    System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
>    System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
>    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1696
> 
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4494.0

**Comment by firetext911** [comment]
how are we doing with this bug? any updates?

**Comment by firetext911** [comment]
I need a frequency pair and can not figure out anything on the website. can someone help me. I need UHF for Trumann Arkansas. 
Thank you

**Comment by firetext911** [comment]
@JoshuaCarroll so I got logged in but the fields will not let you type in them. I get the following error  https://arkansasrepeatercouncil.org/request/
Input string was not in a correct format.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.FormatException: Input string was not in a correct format.

**Comment by JoshuaCarroll** [comment]
Fixed
