### ISSUE TITLE
Map for the website

### ISSUE THREAD

**Issue by JohnMarkRowe** [ArkansasRepeaterCouncil/website#664]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Can you build a map showing location and status?  Might make owners more compliant. 

**Describe alternatives you've considered**

**Additional information**

**Comment by JoshuaCarroll** [comment]
We do have the capability to export the data to KML for mapping, but it shows specific locations for repeaters which many people would prefer not to be available to the public.  On the repeater details pages, we get around that by having a link to a page that displays a general area in which the repeater is located - keeping the specific location secure.  If we used non-specific locations and displayed every repeater, the map would be so busy you wouldn't be able to really glean any actionable data from it.

Thanks for the suggestion, and please do keep them coming!
