### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by firetext911** [ArkansasRepeaterCouncil/website#665]
**Description of the bug**

**Steps to reproduce the behavior**
1. Go to homepage
2. Click on login
3. Click on Create account
4. Enter Information
5. See error

The request was aborted: Could not create SSL/TLS secure channel.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

**Comment by JoshuaCarroll** [comment]
Same as issue #661.  Close to resolution.  Please comment on #661 to stay informed.
